### ISSUE TITLE
Please upload dependencies to huggingface 

### ISSUE THREAD

**Issue by O-O1024** [Sanoojan/REFace#1]
Can't find Other_dependencies/face_recon/epoch_latest.pth .
So many dependencies, not convenient to download.

**Comment by Sanoojan** [comment]
I have added the path for Other_dependencies/face_recon/epoch_latest.pth.
Soon, I will add all the dependencies to the hugging face.

**Comment by Sanoojan** [comment]
All the models are added here https://huggingface.co/Sanoojan/REFace/tree/main

**Comment by O-O1024** [comment]
Thank you!
