### ISSUE TITLE
There is no ddim_guided.py

### ISSUE THREAD

**Issue by pcxdi** [Sanoojan/REFace#4]
Thank you for your contribution to the direction of face change. I would like to ask whether you did not upload ddim_guided.py in ldm, which is very confusing for me, I hope you can answer it for me

**Comment by Sanoojan** [comment]
Thank you for pointing this out. ddim_guided.py is not uploaded as it was for our testing and not used. However, as you mentioned, that is imported in files. I removed all the dependencies of that file and cleaned some other issues in the inference pipeline. Please pull the new updates.

I will close this for now. If any problem persists, feel free to reopen again.
