### ISSUE TITLE
Problems encountered during sh setup.sh execution

### ISSUE THREAD

**Issue by buiquocbao98** [Sanoojan/REFace#5]
Hello,

First of all, thank you for the excellent work on this project!

I encountered two issues while running the sh setup.sh command:

- During the installation, the script asked to install the git repository https://github.com/openai/CLIP.git and gave me three options: (i)gnore, (w)ipe, or (b)ackup. I chose "i" to ignore, but I encountered the following error:
![Screenshot_1](https://github.com/user-attachments/assets/45e72f0f-1b8e-487f-80d0-ea9fc2509687)

- After that, I faced another error as follows:
![Screenshot_2](https://github.com/user-attachments/assets/4c4899d9-664d-4452-a9e6-1afbc9acd659)

Could you please provide guidance on how to resolve these issues?

Thank you in advance!

**Comment by ocastan** [comment]
Hello
I had the same prompt to choose between wipe, backup and ignore for both _Sanoojan/reface/src/taming-transformers_ and _Sanoojan/reface/src/clip_, but I chose wipe after checking the already existing directories were empty.

And now I have the second reported error: looks like the setup is looking for nvdiffrast in _Sanoojan/reface/eval_tool/Deep3DFaceRecon_pytorch_edit/nvdiffrast/_ but after cloning it is instead in _Sanoojan/reface/eval_tool/Deep3DFaceRecon_pytorch_edit/nvdiffrast/nvdiffrast/_

Editing setup.sh, replacing:
```
cd eval_tool/Deep3DFaceRecon_pytorch_edit/nvdiffrast/
git clone https://github.com/NVlabs/nvdiffrast
```
with:
```
cd eval_tool/Deep3DFaceRecon_pytorch_edit/
git clone https://github.com/NVlabs/nvdiffrast
cd nvdiffrast
```

solved my installation problem

**Comment by buiquocbao98** [comment]
Thank you very much for your guidance; I followed it, and it worked perfectly!
