### ISSUE TITLE
Regarding model licenses

### ISSUE THREAD

**Issue by raphael-shin** [Sanoojan/REFace#7]
Hello, @Sanoojan 

Thank you for your work.

In the case of face swapping, are there any models that prohibit commercial use?

I think there shouldn't be any issues except model evaluation. Am I correct?

I would like to hear your opinion.

**Comment by Sanoojan** [comment]
Hi @raphael-shin ,

Thank you for your question. Unfortunately, the model cannot be used for commercial purposes since it was trained on a non-commercial dataset (CelebA). I apologize for any disappointment this may cause.

**Comment by raphael-shin** [comment]
Thank you for your kind answer.
