### ISSUE TITLE
About Result on FFHQ

### ISSUE THREAD

**Issue by superhero-7** [Sanoojan/REFace#8]
Hi!
 Thanks for your open source of your project! I run your project, and get the results on FFHQ bellow:

FID: 5.44
Top1: 64.70%
Top5: 80.80%
Pose: 3.01
Expression: 0.929
It looks Top1 Top5 is bad than the paper report, but FID Pose Expression all better than the result on paper.
Is there anything wrong? And if I remove the mask in the ID retrieval, Top-1 and Top-5 only 53.60% and 74.30% respectively.

**Comment by superhero-7** [comment]
![image](https://github.com/user-attachments/assets/e3cba2f0-fe8d-42c4-b029-ed25aa43585a)
![image](https://github.com/user-attachments/assets/8b1e1026-f387-4a68-acef-416df90c5a90)
I thought maybe there was something wrong with mask? I use esitmate_FFHQ_mask.py script to generate mask, get the above mask (I randomly selected the sixth and 16th result, can compare with your result is the same or not ?), is there anything wrong?

**Comment by Sanoojan** [comment]
I think there is something wrong with the mask selection. Make sure you use this config file: CONFIG="models/REFace/configs/project_ffhq.yaml" 

Attached an image for your reference.
In the config file under test you can modify the mask according to the need. 


![grid-000000000005](https://github.com/user-attachments/assets/751ff033-4751-4780-9ab2-c1eedd749fed)

**Comment by superhero-7** [comment]
[out_20241028_103343.txt](https://github.com/user-attachments/files/17536805/out_20241028_103343.txt)
I updated the mask, I forgot to add the --seg12 parameter before, this time the result seems to be correct. Now I am doing some work related to face swap and would like to have more discussions with you. I wonder if there are other ways to communicate more conveniently? Such as email or Wechat?

**Comment by Sanoojan** [comment]
Great to know that's working. My email address is sanoojan.baliah@mbzuai.ac.ae
